
services:

  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "7214:8080"
    depends_on:
      - postgres
      - redis
  
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

  postgres:
    image: postgres:latest
    container_name: bartender_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass
      POSTGRES_DB: bartenderdb
    volumes:
      - ./postgres_data:/var/lib/postgresql/data  # Persistent data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql # Runs on first startup
    ports:
      - "5442:5432"

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data:
