using Bartender.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace Bartender.Data;

public class AppDbContext(DbContextOptions<AppDbContext> options) : DbContext(options)
{
    public DbSet<Businesses> Businesses { get; set; }
    public DbSet<Places> Places { get; set; }
    public DbSet<Staff> Staff { get; set; }
    public DbSet<Tables> Tables { get; set; }
    public DbSet<MenuItems> MenuItems { get; set; }
    public DbSet<Products> Products { get; set; }
    public DbSet<Orders> Orders { get; set; }
    public DbSet<ProductsPerOrder> ProductsPerOrders { get; set; }
    public DbSet<Customers> Customers { get; set; }
    public DbSet<Reviews> Reviews { get; set; }
    public DbSet<ProductCategory> ProductCategory { get; set; }
    public DbSet<GuestSession> GuestSessions { get; set; }


    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ProductsPerOrder>().HasKey(po => new { po.OrderId, po.MenuItemId });
        modelBuilder.Entity<Reviews>().HasKey(r => new { r.ProductId, r.CustomerId });

        base.OnModelCreating(modelBuilder);
    }

    // uncomment only when you need to debug RAW SQL generated by EF
    //protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    //{
    //    optionsBuilder
    //        .LogTo(Console.WriteLine, LogLevel.Information)
    //        .EnableSensitiveDataLogging();
    //}
}
