name: Azure Auto Deploy

on:
  push:
    branches: 
      [ main ]
    paths:
      - '**'
      - '.github/workflows/bartender-deploy.yml'

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: read

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Log in to GHCR
        run: echo "${{ secrets.BARTENDER_REGISTRY_PASSWORD }}" | docker login ghcr.io -u ${{ secrets.BARTENDER_REGISTRY_USERNAME }} --password-stdin

      - name: Build backend Docker image
        run: docker build -t ghcr.io/${{ secrets.BARTENDER_REGISTRY_USERNAME }}/backend:latest -f ./backend/Dockerfile .

      - name: Push backend Docker image
        run: docker push ghcr.io/${{ secrets.BARTENDER_REGISTRY_USERNAME }}/backend:latest

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.BARTENDER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.BARTENDER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.BARTENDER_AZURE_SUBSCRIPTION_ID }}

      - name: Deploy backend image to Azure Container App
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az containerapp update \
              --name bartender \
              --resource-group bartender-app \
              --image ghcr.io/${{ secrets.BARTENDER_REGISTRY_USERNAME }}/backend:latest \
              --registry-server ghcr.io \
              --registry-username ${{ secrets.BARTENDER_REGISTRY_USERNAME }} \
              --registry-password ${{ secrets.BARTENDER_REGISTRY_PASSWORD }}
