name: Trigger auto deployment for bartender

on:
  push:
    branches: 
      [ main ]
    paths:
      - '**'
      - '.github/workflows/bartender-deploy.yml'

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: read

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.BARTENDER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.BARTENDER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.BARTENDER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to GHCR
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ./
          dockerfilePath: ./backend/Dockerfile
          registryUsername: ${{ secrets.BARTENDER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.BARTENDER_REGISTRY_PASSWORD }}
          containerAppName: bartender
          resourceGroup: bartender-app
          imageToBuild: ghcr.io/mdabcevic/backend:${{ github.sha }}
