name: Run Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3
          
    steps:
      - uses: actions/checkout@v3

      # Backend Tests
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore backend deps
        run: dotnet restore ./backend

      - name: Wait for Redis to be ready
        run: |
          for i in {1..10}; do
            if redis-cli -h localhost ping | grep PONG; then
              echo "Redis is ready!"
              break
            fi
            echo "Waiting for Redis..."
            sleep 1
          done

      - name: Run backend unit tests
        run: dotnet test ./backend/BartenderTests/BartenderTests.csproj --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover

      # TODO: Frontend unit tests

