name: Deploy Smoke Test

on:
  workflow_dispatch:
  push:

jobs:
  deploy-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build and start all services
        run: docker compose up -d --build

      - name: Wait for all containers to become healthy
        run: |
          services=(postgres redis backend frontend)
          for service in "${services[@]}"; do
            echo "⏳ Waiting for $service to be healthy..."
            timeout 60 bash -c \
              'until [ "$(docker inspect -f "{{ .State.Health.Status }}" '"$service"')" == "healthy" ]; do sleep 2; done'
            echo "✅ $service is healthy"
          done

      - name: Show container status
        run: docker compose ps -a

      - name: Fail if any container exited
        run: |
          EXITED=$(docker compose ps --status=exited --format '{{.Name}}')
          if [ -n "$EXITED" ]; then
            echo "❌ Some containers exited unexpectedly:"
            echo "$EXITED"
            docker compose logs
            exit 1
          fi
          echo "✅ No containers exited"

      - name: Check backend health
        run: curl -f http://localhost:7214/health

      - name: Check frontend
        run: curl -f http://localhost:5173

      - name: Clean up
        if: always()
        run: docker compose down -v
