name: Deploy Smoke Test

on:
  workflow_dispatch:
  push:

jobs:
  deploy-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build and start all services
        run: docker-compose up -d --build

      - name: Wait for startup
        run: sleep 20  
      - name: Show container status
        run: docker ps -a

      - name: Ensure all services are healthy
        run: |
          EXITED=$(docker ps -a --filter "status=exited" --format '{{.Names}}')
          if [ -n "$EXITED" ]; then
            echo "❌ Some containers exited unexpectedly:"
            echo "$EXITED"
            docker-compose logs
            exit 1
          fi
          echo "✅ All containers running"

      - name: (Optional) Check backend HTTP health
        run: |
          curl -f http://localhost:7214 || exit 1

      - name: (Optional) Check frontend is up
        run: |
          curl -f http://localhost:5173 || exit 1

      - name: Clean up
        if: always()
        run: docker-compose down -v
